# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redactwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RedactWindow(object):
    def setupUi(self, RedactWindow):
        RedactWindow.setObjectName("RedactWindow")
        RedactWindow.resize(645, 560)
        self.centralWidget = QtWidgets.QWidget(RedactWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.SelectConfigEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.SelectConfigEdit.setEnabled(True)
        self.SelectConfigEdit.setReadOnly(True)
        self.SelectConfigEdit.setObjectName("SelectConfigEdit")
        self.gridLayout.addWidget(self.SelectConfigEdit, 1, 0, 1, 5)
        self.SelectConfigTool = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectConfigTool.sizePolicy().hasHeightForWidth())
        self.SelectConfigTool.setSizePolicy(sizePolicy)
        self.SelectConfigTool.setObjectName("SelectConfigTool")
        self.gridLayout.addWidget(self.SelectConfigTool, 0, 3, 1, 1)
        self.ProgressLabel = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ProgressLabel.setFont(font)
        self.ProgressLabel.setObjectName("ProgressLabel")
        self.gridLayout.addWidget(self.ProgressLabel, 3, 0, 1, 1)
        self.OpenConfigEditorButton = QtWidgets.QToolButton(self.centralWidget)
        self.OpenConfigEditorButton.setObjectName("OpenConfigEditorButton")
        self.gridLayout.addWidget(self.OpenConfigEditorButton, 0, 4, 1, 1)
        self.SelectConfigLabel = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.SelectConfigLabel.setFont(font)
        self.SelectConfigLabel.setObjectName("SelectConfigLabel")
        self.gridLayout.addWidget(self.SelectConfigLabel, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 5)
        self.CancelButton = QtWidgets.QPushButton(self.centralWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout.addWidget(self.CancelButton, 2, 4, 1, 1)
        self.RunButton = QtWidgets.QPushButton(self.centralWidget)
        self.RunButton.setObjectName("RunButton")
        self.gridLayout.addWidget(self.RunButton, 2, 3, 1, 1)
        self.RedactionProgress = QtWidgets.QProgressBar(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RedactionProgress.sizePolicy().hasHeightForWidth())
        self.RedactionProgress.setSizePolicy(sizePolicy)
        self.RedactionProgress.setMaximum(1)
        self.RedactionProgress.setProperty("value", 0)
        self.RedactionProgress.setTextVisible(True)
        self.RedactionProgress.setObjectName("RedactionProgress")
        self.gridLayout.addWidget(self.RedactionProgress, 2, 0, 1, 3)
        RedactWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(RedactWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 645, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        RedactWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(RedactWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        RedactWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(RedactWindow)
        self.statusBar.setObjectName("statusBar")
        RedactWindow.setStatusBar(self.statusBar)
        self.actionCopy = QtWidgets.QAction(RedactWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(RedactWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtWidgets.QAction(RedactWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionExit = QtWidgets.QAction(RedactWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_bca_redtools = QtWidgets.QAction(RedactWindow)
        self.actionAbout_bca_redtools.setObjectName("actionAbout_bca_redtools")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionAbout_bca_redtools)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(RedactWindow)
        QtCore.QMetaObject.connectSlotsByName(RedactWindow)

    def retranslateUi(self, RedactWindow):
        _translate = QtCore.QCoreApplication.translate
        RedactWindow.setWindowTitle(_translate("RedactWindow", "Disk Image Redaction"))
        self.SelectConfigEdit.setPlaceholderText(_translate("RedactWindow", "select a file..."))
        self.SelectConfigTool.setText(_translate("RedactWindow", "Select File.."))
        self.ProgressLabel.setText(_translate("RedactWindow", "Console Output"))
        self.OpenConfigEditorButton.setText(_translate("RedactWindow", "Open Editor"))
        self.SelectConfigLabel.setText(_translate("RedactWindow", "Configuration File"))
        self.CancelButton.setText(_translate("RedactWindow", "Cancel"))
        self.RunButton.setText(_translate("RedactWindow", "Run"))
        self.menuFile.setTitle(_translate("RedactWindow", "File"))
        self.menuEdit.setTitle(_translate("RedactWindow", "Edit"))
        self.menuHelp.setTitle(_translate("RedactWindow", "Help"))
        self.actionCopy.setText(_translate("RedactWindow", "Copy"))
        self.actionPaste.setText(_translate("RedactWindow", "Paste"))
        self.actionCut.setText(_translate("RedactWindow", "Cut"))
        self.actionExit.setText(_translate("RedactWindow", "Exit"))
        self.actionAbout_bca_redtools.setText(_translate("RedactWindow", "About bca-redtools"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RedactWindow = QtWidgets.QMainWindow()
    ui = Ui_RedactWindow()
    ui.setupUi(RedactWindow)
    RedactWindow.show()
    sys.exit(app.exec_())

